[project]
name = "awa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.4",
    "typer>=0.15.3",
]

[project.scripts]
awa = "awa.cli:main"