[project]
name = "calculator-mcp"
version = "0.1.0"
description = "Simple MCP Calculator Server"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
]

[project.scripts]
calculator-mcp = "server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"